# Site settings
title: FS Cosmetics
description: >
    FS Cosmetics is a Philippine makeup brand that had its beginnings in November 2003. The brand is owned by Mr. Edmon Ngo, the scion of a pioneer in the Philippine cosmetic industry, who launched his own company, Cosmetics Revelation Corporation, that honors integrity and excellence and that draws from the solid experience of his parents’ company.

baseurl: ""
url: http://fscosmetics.github.io
# Build settings
markdown: kramdown

#Collections
collections:
    products:
      output: true

    announcement:
      output: true


prose:
  siteurl: "www.fscosmetics.com"
  metadata:
    _video:
      - name: "published"
        field:
          element: 'hidden'
          value: true

      - name: "title"
        field:
          element: "text"
          label: "title"