- title: Face Concealer
  categories: accessories
  description: "Soft and rich concealer stick, that gives total coverage to blemished skin. It also has Vitamin UV-protection and oil-control."
  ratings: 3
  image: http://res.cloudinary.com/ruel/image/upload/v1438575069/fashion21/picture-1.jpg

- title: Face Concealer
  categories: cheeks
  description: "Soft and rich concealer stick, that gives total coverage to blemished skin. It also has Vitamin UV-protection and oil-control."
  ratings: 3
  image: http://res.cloudinary.com/ruel/image/upload/v1438575069/fashion21/picture-8.jpg

- title: Face Concealer
  categories: cheeks
  description: "Soft and rich concealer stick, that gives total coverage to blemished skin. It also has Vitamin UV-protection and oil-control."
  ratings: 3
  image: http://res.cloudinary.com/ruel/image/upload/v1438575069/fashion21/picture-12.jpg

- title: Face Concealer
  categories: cheeks
  description: "Soft and rich concealer stick, that gives total coverage to blemished skin. It also has Vitamin UV-protection and oil-control."
  ratings: 3
  image: http://res.cloudinary.com/ruel/image/upload/v1438575069/fashion21/picture-16.jpg

- title: Face Concealer
  categories: cheeks
  description: "Soft and rich concealer stick, that gives total coverage to blemished skin. It also has Vitamin UV-protection and oil-control."
  ratings: 3
  image: http://res.cloudinary.com/ruel/image/upload/v1438575069/fashion21/picture-20.jpg